name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker Image
      run: |
        docker build -t alopezgsource/login_integracion:1.3 .
        docker build -t alopezgsource/login_integracion:latest .
        
    - name: Push Docker Image
      run: |
        docker push alopezgsource/login_integracion:1.3
        docker push alopezgsource/login_integracion:latest
