name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: docker login
      env:
          DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build  Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/login_integracion:$(date +%s)
        
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/login_integracion:$(date +%s)
      
